In [1]:
import pandas as pd
from keras import Sequential

Using TensorFlow backend.


In [0]:
from keras import layers
from sklearn.model_selection import train_test_split

In [3]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [4]:
import os
os.getcwd()

'/content'

In [5]:
!ls

drive  sample_data


In [0]:
os.chdir('/content/drive/My Drive')

In [7]:
os.getcwd()

'/content/drive/My Drive'

In [0]:
os.chdir('Santander_Kaggle')

In [9]:
!ls

l3bs20.csv	       santander_kaggle.ipynb  test.csv
sample_submission.csv  submission_nn.csv       train.csv


In [0]:
train = pd.read_csv('train.csv')

In [0]:
test = pd.read_csv('test.csv')

In [12]:
train.shape

(200000, 202)

In [13]:
test.shape

(200000, 201)

In [0]:
train_features = train.drop(['target', 'ID_code'], axis=1)

In [0]:
train_targets = train['target']

In [0]:
test_features = test.drop(['ID_code'], axis=1)

In [0]:
X_train, X_test, y_train, y_test = train_test_split(train_features, train_targets, test_size = 0.33, random_state = 2019)

In [0]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [0]:
test_features = sc.transform(test_features)

In [21]:
test_features

array([[ 0.1273355 ,  2.32225532,  0.85089314, ...,  1.9659677 ,
        -0.13042764, -0.52065169],
       [-0.70625919,  0.71161725,  0.22574829, ...,  1.04549385,
         1.0845534 , -1.69605293],
       [-1.7083681 , -2.15458053, -0.21555718, ..., -2.00207078,
         1.33913763, -1.90736296],
       ...,
       [ 0.31488772,  0.9640176 ,  0.1888591 , ...,  0.30996083,
        -1.35358142, -1.82074445],
       [ 0.95228252,  0.2753097 ,  1.11810285, ..., -0.86736927,
        -2.35590506,  0.29523287],
       [-0.06968641,  0.84803586, -0.18257301, ...,  1.55139652,
        -0.50856644, -0.4237621 ]])

In [22]:
X_train

array([[-1.42588893,  1.27550718, -2.12541659, ..., -0.56647433,
        -0.75265235,  0.81014882],
       [-0.50101708, -0.39268983, -0.34635649, ...,  2.08354886,
        -2.36338013, -1.05932252],
       [-0.21669658,  1.4706201 , -1.55099912, ..., -0.07456425,
        -0.69946308,  0.19089171],
       ...,
       [ 0.8168464 ,  0.79180977, -2.0610785 , ...,  0.62940409,
         0.31681402,  0.57370293],
       [-0.10384959,  1.14543189,  0.3580262 , ..., -0.21047678,
         0.36299333,  0.65550717],
       [-1.47981348,  0.83011657, -0.21881769, ..., -0.02705452,
         0.6059829 , -0.655317  ]])

In [23]:
X_test

array([[ 0.9713534 , -0.01068315,  0.07807778, ..., -1.09201002,
        -0.92112378,  1.95343254],
       [-0.37317643,  0.81733118, -1.74037377, ..., -0.15569959,
        -1.33314957, -2.25729904],
       [ 1.54265774,  0.7901067 ,  1.47315661, ..., -0.13519881,
        -1.42368095, -0.68322443],
       ...,
       [-0.91409888, -1.09988471, -0.83524258, ...,  0.58742631,
        -0.66853291,  0.08258981],
       [-2.36930557,  1.39612917, -0.45357401, ..., -0.60975374,
         0.97332438,  0.83090197],
       [-0.9466509 , -0.16803229, -0.79224942, ..., -0.15559112,
        -0.34222125,  0.70176061]])

In [0]:
# Build ANN
from keras.layers.core import Dense

In [0]:
nn_classifier = Sequential()

In [0]:
input_dim = X_train.shape[1]

In [0]:
nn_classifier.add(Dense(activation = "relu", input_dim = input_dim, units = 6, kernel_initializer = "uniform"))
nn_classifier.add(Dense(activation = "relu", units = 6, kernel_initializer = "uniform"))
nn_classifier.add(Dense(activation = "relu", units = 6, kernel_initializer = "uniform"))
nn_classifier.add(Dense(activation = "sigmoid", units = 1, kernel_initializer = "uniform"))

In [0]:
# Compile ANN
nn_classifier.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])

In [0]:
nn_classifier.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 6)                 1206      
_________________________________________________________________
dense_2 (Dense)              (None, 6)                 42        
_________________________________________________________________
dense_3 (Dense)              (None, 6)                 42        
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 7         
_________________________________________________________________
dense_5 (Dense)              (None, 6)                 12        
_________________________________________________________________
dense_6 (Dense)              (None, 6)                 42        
_________________________________________________________________
dense_7 (Dense)              (None, 6)                 42        
__________

In [0]:
nn_classifier.fit(X_train, y_train, epochs = 10, validation_data = (X_test, y_test))

Train on 140000 samples, validate on 60000 samples
Epoch 1/10
140000/140000 [==============================] - 39s 282us/step - loss: 0.2349 - acc: 0.9127 - val_loss: 0.2441 - val_acc: 0.9066
Epoch 2/10
140000/140000 [==============================] - 40s 283us/step - loss: 0.2345 - acc: 0.9126 - val_loss: 0.2463 - val_acc: 0.9082
Epoch 3/10
140000/140000 [==============================] - 40s 284us/step - loss: 0.2342 - acc: 0.9131 - val_loss: 0.2443 - val_acc: 0.9081
Epoch 4/10
140000/140000 [==============================] - 40s 285us/step - loss: 0.2340 - acc: 0.9126 - val_loss: 0.2438 - val_acc: 0.9084
Epoch 5/10
140000/140000 [==============================] - 40s 284us/step - loss: 0.2338 - acc: 0.9134 - val_loss: 0.2447 - val_acc: 0.9083
Epoch 6/10
140000/140000 [==============================] - 40s 285us/step - loss: 0.2336 - acc: 0.9135 - val_loss: 0.2461 - val_acc: 0.9083
Epoch 7/10
140000/140000 [==============================] - 40s 285us/step - loss: 0.2335 - acc: 0.9135

In [0]:
# Make predicitions
pred = nn_classifier.predict(test_features)

In [0]:
pred = nn_classifier.predict(X_test)

In [0]:
pred

array([[0.3264143 ],
       [0.30233592],
       [0.03543723],
       ...,
       [0.011774  ],
       [0.05245551],
       [0.08740807]], dtype=float32)

In [0]:
pred_ = pred[:,0]

In [0]:
len(pred_)

200000

In [0]:
id_code_test = test['ID_code']

In [0]:
len(id_code_test)

200000

In [0]:
foo = pd.DataFrame({"ID_code" : id_code_test})

In [0]:
foo

In [0]:
# To CSV
foo = pd.DataFrame({"ID_code" : id_code_test, "target" : pred_})
#.to_csv("submission_nn.csv", index = False, header = True)

In [0]:
foo.to_csv("submission_nn.csv", index = False, header = True)

In [0]:
# Use KerasClassifier to wrap k-fold cross validation from scikit-learn into our keras model
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

In [0]:
# Function for building ANN classifier - to be used in KerasClassifier parameter 'build_fn'
def build_classifier():
    nn_classifier = Sequential()
    nn_classifier.add(Dense(activation = "relu", input_dim = input_dim, units = 16, kernel_initializer = "uniform"))
    nn_classifier.add(Dense(activation = "relu", units = 16, kernel_initializer = "uniform"))
    nn_classifier.add(Dense(activation = "relu", units = 16, kernel_initializer = "uniform"))
    nn_classifier.add(Dense(activation = "sigmoid", units = 1, kernel_initializer = "uniform"))
    # Compile ANN
    nn_classifier.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])
    return nn_classifier

In [0]:
# Build a classifier using 10-fold cv and find accuracies
classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, nb_epoch = 20)

In [31]:
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = 1)

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
Epoch 1/1
13400/13400 [==============================] - 2s 144us/step
Epoch 1/1
13400/13400 [==============================] - 2s 152us/step
Epoch 1/1
13400/13400 [==============================] - 2s 156us/step
Epoch 1/1
13400/13400 [==============================] - 2s 161us/step
Epoch 1/1
13400/13400 [==============================] - 2s 165us/step
Epoch 1/1
13400/13400 [==============================] - 2s 170us/step
Epoch 1/1
13400/13400 [==============================] - 2s 173us/step
Epoch 1/1
13400/13400 [==============================] - 2s 177us/step
Epoch 1/1
13400/13400 [==============================] - 2s 178us/step
Epoch 1/1
13400/13400 [==============================] - 2s 187us/step


In [33]:
meann = accuracies.mean()
meann

0.9047014851845911

In [0]:
# Doesn't improve

In [0]:
# Improving the model by using dropout regularization
from keras.layers import Dropout

In [0]:
nn_classifier = Sequential()

# Input layer
nn_classifier.add(Dense(activation = "relu", input_dim = input_dim, units = 16, kernel_initializer = "uniform"))
# Add dropout regularization
nn_classifier.add(Dropout(rate=0.1))

# First hidden layer
nn_classifier.add(Dense(activation = "relu", units = 16, kernel_initializer = "uniform"))
# Add dropout regularization
nn_classifier.add(Dropout(rate=0.1))

# Second hidden layer
nn_classifier.add(Dense(activation = "relu", units = 16, kernel_initializer = "uniform"))
# Add dropout regularization
nn_classifier.add(Dropout(rate=0.1))

# Third hidden layer
nn_classifier.add(Dense(activation = "relu", units = 16, kernel_initializer = "uniform"))
# Add dropout regularization
nn_classifier.add(Dropout(rate=0.1))

# Output layer
nn_classifier.add(Dense(activation = "sigmoid", units = 1, kernel_initializer = "uniform"))

# Compile ANN
nn_classifier.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])

In [39]:
nn_classifier.fit(X_train, y_train, epochs = 15, batch_size = 20, validation_data = (X_test, y_test))

Train on 134000 samples, validate on 66000 samples
Epoch 1/15
134000/134000 [==============================] - 41s 307us/step - loss: 0.2412 - acc: 0.9109 - val_loss: 0.2472 - val_acc: 0.9073
Epoch 2/15
134000/134000 [==============================] - 41s 308us/step - loss: 0.2415 - acc: 0.9104 - val_loss: 0.2493 - val_acc: 0.9072
Epoch 3/15
134000/134000 [==============================] - 41s 309us/step - loss: 0.2404 - acc: 0.9108 - val_loss: 0.2473 - val_acc: 0.9078
Epoch 4/15
134000/134000 [==============================] - 41s 309us/step - loss: 0.2401 - acc: 0.9113 - val_loss: 0.2487 - val_acc: 0.9071
Epoch 5/15
134000/134000 [==============================] - 41s 309us/step - loss: 0.2400 - acc: 0.9112 - val_loss: 0.2504 - val_acc: 0.9077
Epoch 6/15
134000/134000 [==============================] - 41s 309us/step - loss: 0.2402 - acc: 0.9115 - val_loss: 0.2471 - val_acc: 0.9075
Epoch 7/15
134000/134000 [==============================] - 42s 310us/step - loss: 0.2401 - acc: 0.9111

In [0]:
nn_classifier = Sequential()

# Input layer
nn_classifier.add(Dense(activation = "relu", input_dim = input_dim, units = 32, kernel_initializer = "uniform"))
# Add dropout regularization
nn_classifier.add(Dropout(rate=0.1))

# First hidden layer
nn_classifier.add(Dense(activation = "relu", units = 32, kernel_initializer = "uniform"))
# Add dropout regularization
nn_classifier.add(Dropout(rate=0.1))

# Second hidden layer
nn_classifier.add(Dense(activation = "relu", units = 32, kernel_initializer = "uniform"))
# Add dropout regularization
nn_classifier.add(Dropout(rate=0.1))

# Third hidden layer
nn_classifier.add(Dense(activation = "relu", units = 32, kernel_initializer = "uniform"))
# Add dropout regularization
nn_classifier.add(Dropout(rate=0.1))

# Output layer
nn_classifier.add(Dense(activation = "sigmoid", units = 1, kernel_initializer = "uniform"))

# Compile ANN
nn_classifier.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])
#nn_classifier.compile(optimizer = "sgd", loss = "binary_crossentropy", metrics = ["accuracy"])

In [27]:
nn_classifier.fit(X_train, y_train, epochs = 6, batch_size = 10, validation_data = (X_test, y_test))

Train on 134000 samples, validate on 66000 samples
Epoch 1/6
134000/134000 [==============================] - 87s 648us/step - loss: 0.2594 - acc: 0.9040 - val_loss: 0.2466 - val_acc: 0.9080
Epoch 2/6
134000/134000 [==============================] - 87s 647us/step - loss: 0.2447 - acc: 0.9094 - val_loss: 0.2506 - val_acc: 0.9081
Epoch 3/6
134000/134000 [==============================] - 87s 647us/step - loss: 0.2394 - acc: 0.9133 - val_loss: 0.2434 - val_acc: 0.9086
Epoch 4/6
134000/134000 [==============================] - 86s 645us/step - loss: 0.2354 - acc: 0.9156 - val_loss: 0.2439 - val_acc: 0.9081
Epoch 5/6
134000/134000 [==============================] - 87s 646us/step - loss: 0.2333 - acc: 0.9165 - val_loss: 0.2440 - val_acc: 0.9072
Epoch 6/6
134000/134000 [==============================] - 87s 646us/step - loss: 0.2306 - acc: 0.9189 - val_loss: 0.2459 - val_acc: 0.9083


In [0]:
def predict_and_save(model, filename):
  id_code_test = test['ID_code']
  # Make predicitions
  pred = model.predict(test_features)
  pred_ = pred[:,0]
  fn = filename + ".csv"
  # To CSV
  foo = pd.DataFrame({"ID_code" : id_code_test, "target" : pred_}).to_csv(fn, index = False, header = True)

In [0]:
predict_and_save(nn_classifier, "l3bs10drop10")

In [0]:
nn_classifier4 = Sequential()

# Input layer
nn_classifier4.add(Dense(activation = "relu", input_dim = input_dim, units = 16, kernel_initializer = "uniform"))
# Add dropout regularization
nn_classifier4.add(Dropout(rate=0.1))

# First hidden layer
nn_classifier4.add(Dense(activation = "relu", units = 16, kernel_initializer = "uniform"))
# Add dropout regularization
nn_classifier4.add(Dropout(rate=0.1))

# Second hidden layer
nn_classifier4.add(Dense(activation = "relu", units = 16, kernel_initializer = "uniform"))
# Add dropout regularization
# nn_classifier2.add(Dropout(rate=0.1))

# Third hidden layer
nn_classifier4.add(Dense(activation = "relu", units = 16, kernel_initializer = "uniform"))
# Add dropout regularization
# nn_classifier2.add(Dropout(rate=0.1))

# Fourth hidden layer
nn_classifier4.add(Dense(activation = "relu", units = 16, kernel_initializer = "uniform"))
# Add dropout regularization
# nn_classifier2.add(Dropout(rate=0.1))

# Output layer
nn_classifier4.add(Dense(activation = "sigmoid", units = 1, kernel_initializer = "uniform"))

# Compile ANN
#nn_classifier2.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])
nn_classifier4.compile(optimizer = "rmsprop", loss = "binary_crossentropy", metrics = ["accuracy"])

In [0]:
nn_classifier5 = Sequential()

# Input layer
nn_classifier5.add(Dense(activation = "relu", input_dim = input_dim, units = 32, kernel_initializer = "uniform"))
# Add dropout regularization
nn_classifier5.add(Dropout(rate=0.1))

# First hidden layer
nn_classifier5.add(Dense(activation = "relu", units = 32, kernel_initializer = "uniform"))
# Add dropout regularization
nn_classifier5.add(Dropout(rate=0.1))

# Second hidden layer
nn_classifier5.add(Dense(activation = "relu", units = 32, kernel_initializer = "uniform"))
# Add dropout regularization
# nn_classifier2.add(Dropout(rate=0.1))

# Third hidden layer
nn_classifier5.add(Dense(activation = "relu", units = 32, kernel_initializer = "uniform"))
# Add dropout regularization
# nn_classifier2.add(Dropout(rate=0.1))

# Fourth hidden layer
nn_classifier5.add(Dense(activation = "relu", units = 32, kernel_initializer = "uniform"))
# Add dropout regularization
# nn_classifier2.add(Dropout(rate=0.1))

# Output layer
nn_classifier5.add(Dense(activation = "sigmoid", units = 1, kernel_initializer = "uniform"))

# Compile ANN
#nn_classifier2.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])
#nn_classifier5.compile(optimizer = "rmsprop", loss = "binary_crossentropy", metrics = ["accuracy"])
nn_classifier5.compile(optimizer = "sgd", loss = "binary_crossentropy", metrics = ["accuracy"])

In [54]:
nn_classifier5.fit(X_train, y_train, epochs = 12, batch_size = 10, validation_data = (X_test, y_test))

Train on 134000 samples, validate on 66000 samples
Epoch 1/12
134000/134000 [==============================] - 86s 638us/step - loss: 0.2607 - acc: 0.9045 - val_loss: 0.2562 - val_acc: 0.9075
Epoch 2/12
134000/134000 [==============================] - 85s 631us/step - loss: 0.2497 - acc: 0.9093 - val_loss: 0.2822 - val_acc: 0.9066
Epoch 3/12
134000/134000 [==============================] - 85s 632us/step - loss: 0.2618 - acc: 0.9096 - val_loss: 0.2523 - val_acc: 0.9074
Epoch 4/12
134000/134000 [==============================] - 85s 634us/step - loss: 0.3326 - acc: 0.9043 - val_loss: 0.2599 - val_acc: 0.9047
Epoch 5/12
134000/134000 [==============================] - 85s 635us/step - loss: 6.9741 - acc: 0.5233 - val_loss: 14.3390 - val_acc: 0.1006
Epoch 6/12
134000/134000 [==============================] - 85s 637us/step - loss: 14.3410 - acc: 0.1004 - val_loss: 14.3388 - val_acc: 0.1006
Epoch 7/12
134000/134000 [==============================] - 85s 636us/step - loss: 14.3410 - acc: 0.

KeyboardInterrupt: ignored